import Head from 'next/head'
import Header from '../components/Header'
import LegBuilder from '../components/LegBuilder'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Algotest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header/>
      <LegBuilder/>
    </div>
  )
}
