import Head from 'next/head'
import Header from '../components/Header'
import LegBuilder from '../components/LegBuilder'
import styled from 'styled-components'
import { useState } from 'react'
import Legs from '../components/Legs'
import { useRecoilState } from 'recoil'
import { globalAtom } from '../atoms/globalAtoms'
import { db } from '../firebase/clientApp';
import { doc, setDoc, getDoc } from "firebase/firestore"; 

export default function Home() {
  const [legs,setLegs]=useState([])
  const [globalState,setGlobalState]=useRecoilState(globalAtom)
  
  const handleSubmit=async(legs)=>{
    await setDoc(doc(db, "legs", "user"), {
      legs
    });
  }

  const fetchDocs=async()=>{
    const legdoc=await getDoc(doc(db, "legs", "user"))
    setLegs(legdoc.data().legs)
  }
  
  return (
    <Container>
      <Head>
        <title>Algotest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header/>
      <LegBuilder legs={legs} setLegs={setLegs} globalState={globalState} setGlobalState={setGlobalState}/>
      <Legs legs={legs} setLegs={setLegs}/>
      <ButtonSection>
          <Fetch onClick={()=>fetchDocs()}>Fetch</Fetch>
          <Submit onClick={()=>handleSubmit(legs)}>Submit</Submit>
      </ButtonSection>
    </Container>
  )
}

const Container = styled.div`
  background-color: #f6f6f6;
  min-height: 100vh;
`;

const ButtonSection = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1.25rem;
  padding: 1rem;
`;

const Fetch = styled.button`
  background-color: #375a9e;
  color: white;
  border: 1px solid #375a9e;
  border-radius: 16px;
  padding: 0.45rem;
`;

const Submit = styled.button`
  color: black;
  background-color: white;
  border: 1px solid white;
  border-radius: 16px;
  padding: 0.45rem;
`;
