import Head from 'next/head'
import Header from '../components/Header'
import LegBuilder from '../components/LegBuilder'
import styled from 'styled-components'
import { useState } from 'react'
import Legs from '../components/Legs'
import { useRecoilState } from 'recoil'
import { globalAtom } from '../atoms/globalAtoms'

export default function Home() {
  const [legs,setLegs]=useState([])
  const [globalState,setGlobalState]=useRecoilState(globalAtom)
  return (
    <Container>
      <Head>
        <title>Algotest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header/>
      <LegBuilder legs={legs} setLegs={setLegs} globalState={globalState} setGlobalState={setGlobalState}/>
      <Legs legs={legs} setLegs={setLegs}/>
      <div>
        <button>Fetch</button>
        <button>Submit</button>
      </div>
    </Container>
  )
}

const Container = styled.div`
  background-color: #f6f6f6;
`;
